// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: internal/proto/cosmos.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Hostname  string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_ComponentStatus
	//	*AgentMessage_HealthResult
	//	*AgentMessage_DeploymentResult
	Message       isAgentMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_internal_proto_cosmos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_cosmos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_cosmos_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AgentMessage) GetMessage() isAgentMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *AgentHeartbeat {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetComponentStatus() *ComponentStatus {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_ComponentStatus); ok {
			return x.ComponentStatus
		}
	}
	return nil
}

func (x *AgentMessage) GetHealthResult() *HealthCheckResult {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_HealthResult); ok {
			return x.HealthResult
		}
	}
	return nil
}

func (x *AgentMessage) GetDeploymentResult() *DeploymentResult {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_DeploymentResult); ok {
			return x.DeploymentResult
		}
	}
	return nil
}

type isAgentMessage_Message interface {
	isAgentMessage_Message()
}

type AgentMessage_Heartbeat struct {
	Heartbeat *AgentHeartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_ComponentStatus struct {
	ComponentStatus *ComponentStatus `protobuf:"bytes,4,opt,name=component_status,json=componentStatus,proto3,oneof"`
}

type AgentMessage_HealthResult struct {
	HealthResult *HealthCheckResult `protobuf:"bytes,5,opt,name=health_result,json=healthResult,proto3,oneof"`
}

type AgentMessage_DeploymentResult struct {
	DeploymentResult *DeploymentResult `protobuf:"bytes,6,opt,name=deployment_result,json=deploymentResult,proto3,oneof"`
}

func (*AgentMessage_Heartbeat) isAgentMessage_Message() {}

func (*AgentMessage_ComponentStatus) isAgentMessage_Message() {}

func (*AgentMessage_HealthResult) isAgentMessage_Message() {}

func (*AgentMessage_DeploymentResult) isAgentMessage_Message() {}

type ControllerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ControllerMessage_Ack
	//	*ControllerMessage_Deployment
	//	*ControllerMessage_Removal
	//	*ControllerMessage_HealthConfig
	Message       isControllerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerMessage) Reset() {
	*x = ControllerMessage{}
	mi := &file_internal_proto_cosmos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerMessage) ProtoMessage() {}

func (x *ControllerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_cosmos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerMessage.ProtoReflect.Descriptor instead.
func (*ControllerMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_cosmos_proto_rawDescGZIP(), []int{1}
}

func (x *ControllerMessage) GetMessage() isControllerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ControllerMessage) GetAck() *Acknowledgment {
	if x != nil {
		if x, ok := x.Message.(*ControllerMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ControllerMessage) GetDeployment() *ComponentDeployment {
	if x != nil {
		if x, ok := x.Message.(*ControllerMessage_Deployment); ok {
			return x.Deployment
		}
	}
	return nil
}

func (x *ControllerMessage) GetRemoval() *ComponentRemoval {
	if x != nil {
		if x, ok := x.Message.(*ControllerMessage_Removal); ok {
			return x.Removal
		}
	}
	return nil
}

func (x *ControllerMessage) GetHealthConfig() *HealthCheckConfig {
	if x != nil {
		if x, ok := x.Message.(*ControllerMessage_HealthConfig); ok {
			return x.HealthConfig
		}
	}
	return nil
}

type isControllerMessage_Message interface {
	isControllerMessage_Message()
}

type ControllerMessage_Ack struct {
	Ack *Acknowledgment `protobuf:"bytes,1,opt,name=ack,proto3,oneof"`
}

type ControllerMessage_Deployment struct {
	Deployment *ComponentDeployment `protobuf:"bytes,2,opt,name=deployment,proto3,oneof"`
}

type ControllerMessage_Removal struct {
	Removal *ComponentRemoval `protobuf:"bytes,3,opt,name=removal,proto3,oneof"`
}

type ControllerMessage_HealthConfig struct {
	HealthConfig *HealthCheckConfig `protobuf:"bytes,4,opt,name=health_config,json=healthConfig,proto3,oneof"`
}

func (*ControllerMessage_Ack) isControllerMessage_Message() {}

func (*ControllerMessage_Deployment) isControllerMessage_Message() {}

func (*ControllerMessage_Removal) isControllerMessage_Message() {}

func (*ControllerMessage_HealthConfig) isControllerMessage_Message() {}

type AgentHeartbeat struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion      string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Metadata          map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ComponentStatuses []*ComponentStatus     `protobuf:"bytes,3,rep,name=component_statuses,json=componentStatuses,proto3" json:"component_statuses,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AgentHeartbeat) Reset() {
	*x = AgentHeartbeat{}
	mi := &file_internal_proto_cosmos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHeartbeat) ProtoMessage() {}

func (x *AgentHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_cosmos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHeartbeat.ProtoReflect.Descriptor instead.
func (*AgentHeartbeat) Descriptor() ([]byte, []int) {
	return file_internal_proto_cosmos_proto_rawDescGZIP(), []int{2}
}

func (x *AgentHeartbeat) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentHeartbeat) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AgentHeartbeat) GetComponentStatuses() []*ComponentStatus {
	if x != nil {
		return x.ComponentStatuses
	}
	return nil
}

type ComponentStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Pid           int32                  `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	LastStartedAt int64                  `protobuf:"varint,5,opt,name=last_started_at,json=lastStartedAt,proto3" json:"last_started_at,omitempty"`
	RestartCount  int32                  `protobuf:"varint,6,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentStatus) Reset() {
	*x = ComponentStatus{}
	mi := &file_internal_proto_cosmos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentStatus) ProtoMessage() {}

func (x *ComponentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_cosmos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentStatus.ProtoReflect.Descriptor instead.
func (*ComponentStatus) Descriptor() ([]byte, []int) {
	return file_internal_proto_cosmos_proto_rawDescGZIP(), []int{3}
}

func (x *ComponentStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComponentStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ComponentStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ComponentStatus) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ComponentStatus) GetLastStartedAt() int64 {
	if x != nil {
		return x.LastStartedAt
	}
	return 0
}

func (x *ComponentStatus) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

type HealthCheckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComponentName string                 `protobuf:"bytes,1,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	CheckType     string                 `protobuf:"bytes,2,opt,name=check_type,json=checkType,proto3" json:"check_type,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResult) Reset() {
	*x = HealthCheckResult{}
	mi := &file_internal_proto_cosmos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResult) ProtoMessage() {}

func (x *HealthCheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_cosmos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResult.ProtoReflect.Descriptor instead.
func (*HealthCheckResult) Descriptor() ([]byte, []int) {
	return file_internal_proto_cosmos_proto_rawDescGZIP(), []int{4}
}

func (x *HealthCheckResult) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *HealthCheckResult) GetCheckType() string {
	if x != nil {
		return x.CheckType
	}
	return ""
}

func (x *HealthCheckResult) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *HealthCheckResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResult) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type DeploymentResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComponentName string                 `protobuf:"bytes,1,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentResult) Reset() {
	*x = DeploymentResult{}
	mi := &file_internal_proto_cosmos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentResult) ProtoMessage() {}

func (x *DeploymentResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_cosmos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentResult.ProtoReflect.Descriptor instead.
func (*DeploymentResult) Descriptor() ([]byte, []int) {
	return file_internal_proto_cosmos_proto_rawDescGZIP(), []int{5}
}

func (x *DeploymentResult) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *DeploymentResult) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *DeploymentResult) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *DeploymentResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeploymentResult) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Acknowledgment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Acknowledgment) Reset() {
	*x = Acknowledgment{}
	mi := &file_internal_proto_cosmos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acknowledgment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledgment) ProtoMessage() {}

func (x *Acknowledgment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_cosmos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledgment.ProtoReflect.Descriptor instead.
func (*Acknowledgment) Descriptor() ([]byte, []int) {
	return file_internal_proto_cosmos_proto_rawDescGZIP(), []int{6}
}

func (x *Acknowledgment) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Acknowledgment) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ComponentDeployment struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ComponentName      string                 `protobuf:"bytes,1,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	ComponentType      string                 `protobuf:"bytes,2,opt,name=component_type,json=componentType,proto3" json:"component_type,omitempty"`
	Hash               string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	ContentUrl         string                 `protobuf:"bytes,4,opt,name=content_url,json=contentUrl,proto3" json:"content_url,omitempty"`
	ContentUrlEncoding string                 `protobuf:"bytes,5,opt,name=content_url_encoding,json=contentUrlEncoding,proto3" json:"content_url_encoding,omitempty"`
	Content            string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	HealthCheck        *HealthCheckConfig     `protobuf:"bytes,7,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	Env                map[string]string      `protobuf:"bytes,8,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Args               []string               `protobuf:"bytes,9,rep,name=args,proto3" json:"args,omitempty"`
	Managed            bool                   `protobuf:"varint,10,opt,name=managed,proto3" json:"managed,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ComponentDeployment) Reset() {
	*x = ComponentDeployment{}
	mi := &file_internal_proto_cosmos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentDeployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentDeployment) ProtoMessage() {}

func (x *ComponentDeployment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_cosmos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentDeployment.ProtoReflect.Descriptor instead.
func (*ComponentDeployment) Descriptor() ([]byte, []int) {
	return file_internal_proto_cosmos_proto_rawDescGZIP(), []int{7}
}

func (x *ComponentDeployment) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *ComponentDeployment) GetComponentType() string {
	if x != nil {
		return x.ComponentType
	}
	return ""
}

func (x *ComponentDeployment) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ComponentDeployment) GetContentUrl() string {
	if x != nil {
		return x.ContentUrl
	}
	return ""
}

func (x *ComponentDeployment) GetContentUrlEncoding() string {
	if x != nil {
		return x.ContentUrlEncoding
	}
	return ""
}

func (x *ComponentDeployment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ComponentDeployment) GetHealthCheck() *HealthCheckConfig {
	if x != nil {
		return x.HealthCheck
	}
	return nil
}

func (x *ComponentDeployment) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ComponentDeployment) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ComponentDeployment) GetManaged() bool {
	if x != nil {
		return x.Managed
	}
	return false
}

type ComponentRemoval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComponentName string                 `protobuf:"bytes,1,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentRemoval) Reset() {
	*x = ComponentRemoval{}
	mi := &file_internal_proto_cosmos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentRemoval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentRemoval) ProtoMessage() {}

func (x *ComponentRemoval) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_cosmos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentRemoval.ProtoReflect.Descriptor instead.
func (*ComponentRemoval) Descriptor() ([]byte, []int) {
	return file_internal_proto_cosmos_proto_rawDescGZIP(), []int{8}
}

func (x *ComponentRemoval) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

type HealthCheckConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ComponentName   string                 `protobuf:"bytes,1,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	Type            string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Endpoint        string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	IntervalSeconds int32                  `protobuf:"varint,4,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	TimeoutSeconds  int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Retries         int32                  `protobuf:"varint,6,opt,name=retries,proto3" json:"retries,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthCheckConfig) Reset() {
	*x = HealthCheckConfig{}
	mi := &file_internal_proto_cosmos_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckConfig) ProtoMessage() {}

func (x *HealthCheckConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_cosmos_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckConfig.ProtoReflect.Descriptor instead.
func (*HealthCheckConfig) Descriptor() ([]byte, []int) {
	return file_internal_proto_cosmos_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckConfig) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *HealthCheckConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HealthCheckConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *HealthCheckConfig) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *HealthCheckConfig) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *HealthCheckConfig) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

var File_internal_proto_cosmos_proto protoreflect.FileDescriptor

const file_internal_proto_cosmos_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/proto/cosmos.proto\x12\x06cosmos\"\xdc\x02\n" +
	"\fAgentMessage\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x126\n" +
	"\theartbeat\x18\x03 \x01(\v2\x16.cosmos.AgentHeartbeatH\x00R\theartbeat\x12D\n" +
	"\x10component_status\x18\x04 \x01(\v2\x17.cosmos.ComponentStatusH\x00R\x0fcomponentStatus\x12@\n" +
	"\rhealth_result\x18\x05 \x01(\v2\x19.cosmos.HealthCheckResultH\x00R\fhealthResult\x12G\n" +
	"\x11deployment_result\x18\x06 \x01(\v2\x18.cosmos.DeploymentResultH\x00R\x10deploymentResultB\t\n" +
	"\amessage\"\x81\x02\n" +
	"\x11ControllerMessage\x12*\n" +
	"\x03ack\x18\x01 \x01(\v2\x16.cosmos.AcknowledgmentH\x00R\x03ack\x12=\n" +
	"\n" +
	"deployment\x18\x02 \x01(\v2\x1b.cosmos.ComponentDeploymentH\x00R\n" +
	"deployment\x124\n" +
	"\aremoval\x18\x03 \x01(\v2\x18.cosmos.ComponentRemovalH\x00R\aremoval\x12@\n" +
	"\rhealth_config\x18\x04 \x01(\v2\x19.cosmos.HealthCheckConfigH\x00R\fhealthConfigB\t\n" +
	"\amessage\"\xfc\x01\n" +
	"\x0eAgentHeartbeat\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12@\n" +
	"\bmetadata\x18\x02 \x03(\v2$.cosmos.AgentHeartbeat.MetadataEntryR\bmetadata\x12F\n" +
	"\x12component_statuses\x18\x03 \x03(\v2\x17.cosmos.ComponentStatusR\x11componentStatuses\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb6\x01\n" +
	"\x0fComponentStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\x05R\x03pid\x12&\n" +
	"\x0flast_started_at\x18\x05 \x01(\x03R\rlastStartedAt\x12#\n" +
	"\rrestart_count\x18\x06 \x01(\x05R\frestartCount\"\xa9\x01\n" +
	"\x11HealthCheckResult\x12%\n" +
	"\x0ecomponent_name\x18\x01 \x01(\tR\rcomponentName\x12\x1d\n" +
	"\n" +
	"check_type\x18\x02 \x01(\tR\tcheckType\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\xa7\x01\n" +
	"\x10DeploymentResult\x12%\n" +
	"\x0ecomponent_name\x18\x01 \x01(\tR\rcomponentName\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"D\n" +
	"\x0eAcknowledgment\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc0\x03\n" +
	"\x13ComponentDeployment\x12%\n" +
	"\x0ecomponent_name\x18\x01 \x01(\tR\rcomponentName\x12%\n" +
	"\x0ecomponent_type\x18\x02 \x01(\tR\rcomponentType\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x1f\n" +
	"\vcontent_url\x18\x04 \x01(\tR\n" +
	"contentUrl\x120\n" +
	"\x14content_url_encoding\x18\x05 \x01(\tR\x12contentUrlEncoding\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12<\n" +
	"\fhealth_check\x18\a \x01(\v2\x19.cosmos.HealthCheckConfigR\vhealthCheck\x126\n" +
	"\x03env\x18\b \x03(\v2$.cosmos.ComponentDeployment.EnvEntryR\x03env\x12\x12\n" +
	"\x04args\x18\t \x03(\tR\x04args\x12\x18\n" +
	"\amanaged\x18\n" +
	" \x01(\bR\amanaged\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\x10ComponentRemoval\x12%\n" +
	"\x0ecomponent_name\x18\x01 \x01(\tR\rcomponentName\"\xd8\x01\n" +
	"\x11HealthCheckConfig\x12%\n" +
	"\x0ecomponent_name\x18\x01 \x01(\tR\rcomponentName\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12)\n" +
	"\x10interval_seconds\x18\x04 \x01(\x05R\x0fintervalSeconds\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x12\x18\n" +
	"\aretries\x18\x06 \x01(\x05R\aretries2^\n" +
	"\x10CosmosController\x12J\n" +
	"\x13StreamAgentMessages\x12\x14.cosmos.AgentMessage\x1a\x19.cosmos.ControllerMessage(\x010\x01B7Z5github.com/metorial/fleet/cosmos/internal/proto;protob\x06proto3"

var (
	file_internal_proto_cosmos_proto_rawDescOnce sync.Once
	file_internal_proto_cosmos_proto_rawDescData []byte
)

func file_internal_proto_cosmos_proto_rawDescGZIP() []byte {
	file_internal_proto_cosmos_proto_rawDescOnce.Do(func() {
		file_internal_proto_cosmos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_cosmos_proto_rawDesc), len(file_internal_proto_cosmos_proto_rawDesc)))
	})
	return file_internal_proto_cosmos_proto_rawDescData
}

var file_internal_proto_cosmos_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_proto_cosmos_proto_goTypes = []any{
	(*AgentMessage)(nil),        // 0: cosmos.AgentMessage
	(*ControllerMessage)(nil),   // 1: cosmos.ControllerMessage
	(*AgentHeartbeat)(nil),      // 2: cosmos.AgentHeartbeat
	(*ComponentStatus)(nil),     // 3: cosmos.ComponentStatus
	(*HealthCheckResult)(nil),   // 4: cosmos.HealthCheckResult
	(*DeploymentResult)(nil),    // 5: cosmos.DeploymentResult
	(*Acknowledgment)(nil),      // 6: cosmos.Acknowledgment
	(*ComponentDeployment)(nil), // 7: cosmos.ComponentDeployment
	(*ComponentRemoval)(nil),    // 8: cosmos.ComponentRemoval
	(*HealthCheckConfig)(nil),   // 9: cosmos.HealthCheckConfig
	nil,                         // 10: cosmos.AgentHeartbeat.MetadataEntry
	nil,                         // 11: cosmos.ComponentDeployment.EnvEntry
}
var file_internal_proto_cosmos_proto_depIdxs = []int32{
	2,  // 0: cosmos.AgentMessage.heartbeat:type_name -> cosmos.AgentHeartbeat
	3,  // 1: cosmos.AgentMessage.component_status:type_name -> cosmos.ComponentStatus
	4,  // 2: cosmos.AgentMessage.health_result:type_name -> cosmos.HealthCheckResult
	5,  // 3: cosmos.AgentMessage.deployment_result:type_name -> cosmos.DeploymentResult
	6,  // 4: cosmos.ControllerMessage.ack:type_name -> cosmos.Acknowledgment
	7,  // 5: cosmos.ControllerMessage.deployment:type_name -> cosmos.ComponentDeployment
	8,  // 6: cosmos.ControllerMessage.removal:type_name -> cosmos.ComponentRemoval
	9,  // 7: cosmos.ControllerMessage.health_config:type_name -> cosmos.HealthCheckConfig
	10, // 8: cosmos.AgentHeartbeat.metadata:type_name -> cosmos.AgentHeartbeat.MetadataEntry
	3,  // 9: cosmos.AgentHeartbeat.component_statuses:type_name -> cosmos.ComponentStatus
	9,  // 10: cosmos.ComponentDeployment.health_check:type_name -> cosmos.HealthCheckConfig
	11, // 11: cosmos.ComponentDeployment.env:type_name -> cosmos.ComponentDeployment.EnvEntry
	0,  // 12: cosmos.CosmosController.StreamAgentMessages:input_type -> cosmos.AgentMessage
	1,  // 13: cosmos.CosmosController.StreamAgentMessages:output_type -> cosmos.ControllerMessage
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_internal_proto_cosmos_proto_init() }
func file_internal_proto_cosmos_proto_init() {
	if File_internal_proto_cosmos_proto != nil {
		return
	}
	file_internal_proto_cosmos_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_ComponentStatus)(nil),
		(*AgentMessage_HealthResult)(nil),
		(*AgentMessage_DeploymentResult)(nil),
	}
	file_internal_proto_cosmos_proto_msgTypes[1].OneofWrappers = []any{
		(*ControllerMessage_Ack)(nil),
		(*ControllerMessage_Deployment)(nil),
		(*ControllerMessage_Removal)(nil),
		(*ControllerMessage_HealthConfig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_cosmos_proto_rawDesc), len(file_internal_proto_cosmos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_cosmos_proto_goTypes,
		DependencyIndexes: file_internal_proto_cosmos_proto_depIdxs,
		MessageInfos:      file_internal_proto_cosmos_proto_msgTypes,
	}.Build()
	File_internal_proto_cosmos_proto = out.File
	file_internal_proto_cosmos_proto_goTypes = nil
	file_internal_proto_cosmos_proto_depIdxs = nil
}
