// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: internal/proto/cosmos.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CosmosController_StreamAgentMessages_FullMethodName = "/cosmos.CosmosController/StreamAgentMessages"
)

// CosmosControllerClient is the client API for CosmosController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CosmosControllerClient interface {
	StreamAgentMessages(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ControllerMessage], error)
}

type cosmosControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewCosmosControllerClient(cc grpc.ClientConnInterface) CosmosControllerClient {
	return &cosmosControllerClient{cc}
}

func (c *cosmosControllerClient) StreamAgentMessages(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ControllerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CosmosController_ServiceDesc.Streams[0], CosmosController_StreamAgentMessages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, ControllerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CosmosController_StreamAgentMessagesClient = grpc.BidiStreamingClient[AgentMessage, ControllerMessage]

// CosmosControllerServer is the server API for CosmosController service.
// All implementations must embed UnimplementedCosmosControllerServer
// for forward compatibility.
type CosmosControllerServer interface {
	StreamAgentMessages(grpc.BidiStreamingServer[AgentMessage, ControllerMessage]) error
	mustEmbedUnimplementedCosmosControllerServer()
}

// UnimplementedCosmosControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCosmosControllerServer struct{}

func (UnimplementedCosmosControllerServer) StreamAgentMessages(grpc.BidiStreamingServer[AgentMessage, ControllerMessage]) error {
	return status.Errorf(codes.Unimplemented, "method StreamAgentMessages not implemented")
}
func (UnimplementedCosmosControllerServer) mustEmbedUnimplementedCosmosControllerServer() {}
func (UnimplementedCosmosControllerServer) testEmbeddedByValue()                          {}

// UnsafeCosmosControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CosmosControllerServer will
// result in compilation errors.
type UnsafeCosmosControllerServer interface {
	mustEmbedUnimplementedCosmosControllerServer()
}

func RegisterCosmosControllerServer(s grpc.ServiceRegistrar, srv CosmosControllerServer) {
	// If the following call pancis, it indicates UnimplementedCosmosControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CosmosController_ServiceDesc, srv)
}

func _CosmosController_StreamAgentMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CosmosControllerServer).StreamAgentMessages(&grpc.GenericServerStream[AgentMessage, ControllerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CosmosController_StreamAgentMessagesServer = grpc.BidiStreamingServer[AgentMessage, ControllerMessage]

// CosmosController_ServiceDesc is the grpc.ServiceDesc for CosmosController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CosmosController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.CosmosController",
	HandlerType: (*CosmosControllerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAgentMessages",
			Handler:       _CosmosController_StreamAgentMessages_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/proto/cosmos.proto",
}
